#!/bin/bash
# for iOS 5 - 7
kpatch=0 #iOS7_remount_rootfs
ios5=0
### Mount Root/Data-FS
if [ -e "/dev/rdisk0s2" ]; then
echo "Not supported"
nvram -d boot-partition
nvram -d boot-ramdisk
sleep 1s
reboot_
fi

mount_hfs /dev/disk0s1s1 /mnt1
if [ ! -e "/dev/rdisk0s1s3" ]; then
mount_hfs /dev/disk0s1s2 /mnt1/private/var
else
# fuck ios 5
echo "iOS 5" > /dev/console
ios5=1
mount_hfs /dev/disk0s1s3 /mnt1/private/var
fi
sleep 1s

### Disable OTA Update
rm -rf /mnt1/System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist
rm -rf /mnt1/System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist

#####################################################################
########################## Install Exploit ##########################
#####################################################################
Data_GUID="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Partition unique GUID: //p')"
LogicalSector="$((echo -e "p\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Logical sector size: //p' | sed 's/ .*//')"
System_LastSector="$((echo -e "i\n1\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Last sector: //p' | sed 's/ .*//')"
Data_LastSector="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Last sector: //p' | sed 's/ .*//')"
Data_Attributeflags="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*flags: //p')"
Exploit_LastSector="$((524288/$LogicalSector))"
BOOTLOADER="$((8388608/$LogicalSector))"
NOTSD="$(($Exploit_LastSector+$BOOTLOADER))"
Data_LastSectorSD="$(($Data_LastSector-$BOOTLOADER))"
New_Data_LastSector="$(($Data_LastSector-$NOTSD))"
New_Data_SectorSize="$(($New_Data_LastSector-$System_LastSector))"
New_Data_Size="$(($New_Data_SectorSize*$LogicalSector))"


### Resize Data-FS
hfs_resize /mnt1/private/var $New_Data_Size
sleep 1s

### Install exploit_1st
if [ "$Data_Attributeflags" = "0001000000000000" ]; then
echo -e "d\n2\nn\n\n$New_Data_LastSector\n\nc\n2\nData\nx\na\n2\n48\n\nc\n2\n$Data_GUID\ns\n4\nm\nn\n3\n\n$Data_LastSectorSD\n\nn\n4\n\n$Data_LastSector\n\nw\nY\n" | gptfdisk /dev/rdisk0s1
else
echo -e "d\n2\nn\n\n$New_Data_LastSector\n\nc\n2\nData\nx\na\n2\n48\n49\n\nc\n2\n$Data_GUID\ns\n4\nm\nn\n3\n\n$Data_LastSectorSD\n\nn\n4\n\n$Data_LastSector\n\nw\nY\n" | gptfdisk /dev/rdisk0s1
fi

sleep 1s

if [ $ios5 == 0 ]; then
newfs_hfs -s -v exploit /dev/rdisk0s1s3
newfs_hfs -s -v bootloader /dev/rdisk0s1s4
sleep 1s
fsck_hfs -f /dev/rdisk0s1s3
fsck_hfs -f /dev/rdisk0s1s4
sleep 2s

### Install exploit_2nd
dd of=/dev/rdisk0s1s3 if=/ramdiskH.dmg bs=512k count=1
sleep 1s
mount_hfs /dev/disk0s1s4 /mnt2
fi

if [ $ios5 == 1 ]; then
# *fuck ios 5
#
# --- restore log by serial ---
# LwVM::_partitionsFromConfig - loaded configuration for 2 partitions
# Remounting LwVM volumes that were previously mounted
# entering _mount_lwvm_devices
# libpartition, mounting '/dev/disk0s1s1' at '/mnt1'
# executing /sbin/mount -t hfs /dev/disk0s1s1 /mnt1
# libpartition, mounting '/dev/disk0s1s3' at '/mnt2'
# executing /sbin/mount -t hfs /dev/disk0s1s3 /mnt2
# Successfully resized the system partition for content
# entering maximize_data_partition
# entering adjust_partition
# ...
# Initialized /dev/rdisk0s1s4 as a 8 MB HFS Plus volume
# Initialized /dev/rdisk0s1s5 as a 512 KB HFS Plus volume
# -- end ---
#
# For some reason, when running time /sbin/reboot, the disks will be arranged as follows:
# -+ /dev/rdisk0s1s1: System
# -+ /dev/rdisk0s1s3: Data   (Actually: /dev/rdisk0s1s2)
# Also, if divide the partition into four, it will be like this.
# -+ /dev/rdisk0s1s4:        (Actually: /dev/rdisk0s1s4)
# -+ /dev/rdisk0s1s5:        (Actually: /dev/rdisk0s1s3)
# In short, /dev/rdisk0s1s3 is data partition, /dev/rdisk0s1s4 is bootloader partition, and /dev/ridisk0s1s5 is exploit partition.
#
newfs_hfs -s -v bootloader /dev/rdisk0s1s4
newfs_hfs -s -v exploit /dev/rdisk0s1s5
sleep 2s
fsck_hfs -f /dev/rdisk0s1s4
fsck_hfs -f /dev/rdisk0s1s5
sleep 2s

# Install exploit_2nd (fuck ios 5)
dd of=/dev/rdisk0s1s5 if=/ramdiskH.dmg bs=512k count=1
sleep 1s
mount_hfs /dev/disk0s1s4 /mnt2
fi

nvram boot-partition=2

sleep 1s

if [ $kpatch == 1 ]; then #iOS7_remount_rootfs
mount -u -o rw /
mv -v /iBoot /mnt2/iBEC
else
dd of=/mnt2/iBEC if=/iBoot bs=512k #kpatchless
fi
sleep 1s

### Reboot ###
reboot_
