#!/bin/bash

kpatch=0
ios5=0

if [ -e "/dev/rdisk0s2" ]; then
echo "Not supported"
nvram -d boot-partition
nvram -d boot-ramdisk
sleep 1s
reboot_
fi

mount_hfs /dev/disk0s1s1 /mnt1
if [ ! -e "/dev/rdisk0s1s3" ]; then
mount_hfs /dev/disk0s1s2 /mnt1/private/var
else
ios5=1
mount_hfs /dev/disk0s1s3 /mnt1/private/var
fi
sleep 1s

rm -rf /mnt1/System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist
rm -rf /mnt1/System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist

Data_GUID="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Partition unique GUID: //p')"
LogicalSector="$((echo -e "p\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Logical sector size: //p' | sed 's/ .*//')"
System_LastSector="$((echo -e "i\n1\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Last sector: //p' | sed 's/ .*//')"
Data_LastSector="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*Last sector: //p' | sed 's/ .*//')"
Data_Attributeflags="$((echo -e "i\n2\nq") | gptfdisk /dev/rdisk0s1 2>/dev/null | sed -n -e 's/^.*flags: //p')"
Exploit_LastSector="$((524288/$LogicalSector))"
BOOTLOADER="$((8388608/$LogicalSector))"
NOTSD="$(($Exploit_LastSector+$BOOTLOADER))"
Data_LastSectorSD="$(($Data_LastSector-$BOOTLOADER))"
New_Data_LastSector="$(($Data_LastSector-$NOTSD))"
New_Data_SectorSize="$(($New_Data_LastSector-$System_LastSector))"
New_Data_Size="$(($New_Data_SectorSize*$LogicalSector))"


hfs_resize /mnt1/private/var $New_Data_Size
sleep 1s

if [ "$Data_Attributeflags" = "0001000000000000" ]; then
echo -e "d\n2\nn\n\n$New_Data_LastSector\n\nc\n2\nData\nx\na\n2\n48\n\nc\n2\n$Data_GUID\ns\n4\nm\nn\n3\n\n$Data_LastSectorSD\n\nn\n4\n\n$Data_LastSector\n\nw\nY\n" | gptfdisk /dev/rdisk0s1
else
echo -e "d\n2\nn\n\n$New_Data_LastSector\n\nc\n2\nData\nx\na\n2\n48\n49\n\nc\n2\n$Data_GUID\ns\n4\nm\nn\n3\n\n$Data_LastSectorSD\n\nn\n4\n\n$Data_LastSector\n\nw\nY\n" | gptfdisk /dev/rdisk0s1
fi

sleep 1s

if [ $ios5 == 0 ]; then
newfs_hfs -s -v exploit /dev/rdisk0s1s3
newfs_hfs -s -v bootloader /dev/rdisk0s1s4
sleep 1s
fsck_hfs -f /dev/rdisk0s1s3
fsck_hfs -f /dev/rdisk0s1s4
sleep 2s

dd of=/dev/rdisk0s1s3 if=/ramdiskH.dmg bs=512k count=1
sleep 1s
mount_hfs /dev/disk0s1s4 /mnt2
fi

if [ $ios5 == 1 ]; then
newfs_hfs -s -v bootloader /dev/rdisk0s1s4
newfs_hfs -s -v exploit /dev/rdisk0s1s5
sleep 2s
fsck_hfs -f /dev/rdisk0s1s4
fsck_hfs -f /dev/rdisk0s1s5
sleep 2s

dd of=/dev/rdisk0s1s5 if=/ramdiskH.dmg bs=512k count=1
sleep 1s
mount_hfs /dev/disk0s1s4 /mnt2
fi

nvram boot-partition=2
#nvram boot-args="cs_enforcement_disable=1 amfi_get_out_of_my_way=1 -v"


sleep 1s

if [ $kpatch == 1 ]; then
mount -u -o rw /
mv -v /iBoot /mnt2/.jbd
else
dd of=/mnt2/.jbd if=/iBoot bs=512k
fi
sleep 1s

### Reboot ###
reboot_
